name: Sync and Convert Kdroidwin Filter

on:
  schedule:
    - cron: '0 20 * * *' # 毎日日本時間の朝5時に自動実行
  workflow_dispatch: # 手動実行ボタンを有効化

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を付与

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Conversion Script
        run: python scripts/convert.py

      - name: Commit and Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 💡 保存する対象ファイルを新しい名前に書き換え
          git add "dist/uB-filter-by-kdroidwin.txt"
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update AdGuard filter" && git push)
